[tool.poetry]
authors = ["Nelson Lee <leelhn2345@outlook.com>"]
description = ""
name = "python-project-template"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
ipykernel = "^6.22.0"
isort = "^5.12.0"
mypy = "^1.2.0"
pre-commit = "^3.2.2"
ruff = "^0.0.261"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.isort]
profile = "black"

[tool.ruff]
